name: Deploy Dev

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          environment: development
          workingDirectory: app
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
        env:
          DATABASE_URL: ${{ secrets.DEVELOPMENT_DATABASE_URL }}
